# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d684bb65f68016b68be7f89083159e137a0c6442db7d99033d1f6c9e8343f1b72d96c1d59c3e6df04bcf5c75f1e4cd743a3df7c15ac29891eee5b8b24bab5872

test:
  secret_key_base: cf88fab75ba19b49505fe61622dac87ae37c66230dffcd5606a784a9a01ad1ce4493effa800dad64df15454ec2d07462705eab06ebb9f5cdf245e13a28cf2669

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
